#!/bin/sh
#
# NOTE:  This script reads the server name from /etc/sysadmin-logs.conf
#       if that doesn't exist localhost is assumed
#


#
# Read the config-file, if it exists.
#
if [ -e /etc/sysadmin-logs.conf ]; then
   . /etc/sysadmin-logs.conf
fi

#
#  Get the server name
#
if [ -z "$server" ]; then
    server=localhost
fi


#
#
#  Ensure we have curl
#
if ( ! which curl >/dev/null 2>/dev/null ); then
    echo "Failed to find 'curl' executable"
    exit 1
fi

#
#  Make the request, and exit with the exit-code from curl.
#
curl http://${server}:9977/recent
exit $?