#!/bin/sh


#
#  Ensure we have curl
#
if ( ! which curl >/dev/null 2>/dev/null ); then
    echo "Failed to find 'curl' executable"
    exit 1
fi

#
#  Ensure we got a message
#
if [ -z "$1" ]; then
   echo "Usage: $0 msg .."
   exit 1
fi

#
#  POST, and keep curls exit-code.
#
curl -k -X POST http://localhost:9977/ -d msg="$*" user=$USER
exit $?
