#!/bin/sh


#
# Read the config-file, if it exists.
#
if [ -e /etc/sysadmin-logs.conf ]; then
   . /etc/sysadmin-logs.conf
fi

#
#  Get the server name
#
if [ -z "$server" ]; then
    server=localhost
fi

#
#  Ensure we have curl
#
if ( ! which curl >/dev/null 2>/dev/null ); then
    echo "Failed to find 'curl' executable"
    exit 1
fi

#
#  Ensure we got a message
#
if [ -z "$1" ]; then
   echo "Usage: $0 msg .."
   exit 1
fi

#
#  POST, and keep curls exit-code.
#
curl -k -X POST http://${server}:9977/ -d msg="$*" -d user="$USER"
exit $?
